import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import NavBar from "~/components/NavBar";
import Providers from "~/lib/contexts";
import { getServerAuth } from "~/lib/session";
import "~/styles/tailwind.css";
import { use } from "react";

const font = Nunito({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Hello, keyboard",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps) {
  const session = await getServerAuth();

  return (
    <html lang="en" className={font.className}>
      <body draggable={false}>
        <section className="container mx-auto flex min-h-screen max-w-7xl gap-5 p-10">
          <nav className="flex min-w-max flex-col gap-2">
            {session?.user && <NavBar />}
          </nav>
          <main className="flex w-full justify-center">
            <Providers session={session}>{children}</Providers>
          </main>
        </section>
      </body>
    </html>
  );
}
