import { type Metadata } from "next";
import { NavBar } from "~/components/server";
import Providers from "~/lib/contexts";
import "~/styles/tailwind.css";

export const metadata: Metadata = {
  title: "Hello, keyboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className="bg-mix">
        <section className="flex">
          <Providers>
            <NavBar className="flex min-w-max flex-col items-center gap-8 border-r-2 border-gray-900 p-1 py-3 duration-700 md:p-3 " />
            <main className="flex w-full justify-center py-3">{children}</main>
          </Providers>
        </section>
      </body>
    </html>
  );
}
